apiVersion: 1

datasources:
- orgId: 1
  name: EVCC
  type: influxdb
  typeName: InfluxDB
  access: proxy
  url: http://influxdb2:8086
  jsonData:
    dbName: evcc
    httpHeaderName1: 'Authorization'
  secureJsonData:
    httpHeaderValue1: 'Token %%TOKEN%%'
  readOnly: false

